/**
 * Extracts message flow traces showing how ClientMessage types flow
 * through the system to produce ServerMessage responses.
 *
 * This is a hand-crafted extraction based on the known dispatch patterns:
 * 1. ClientMessage.type → onMessage() switch in websocket.ts
 * 2. game.enqueue(Command) → processCommands() switch in gameLoop.ts
 * 3. GameEvent → broadcastGameEvent() switch in websocket.ts → ServerMessage
 *
 * The flows are derived from static analysis of the switch/case structures
 * combined with knowledge of the architecture. Each flow traces the complete
 * path a client message takes through the system.
 */

import type { MessageFlow, MessageFlowGroup } from "./types.js";

/**
 * Build the full set of message flows.
 *
 * These are defined declaratively based on code analysis rather than
 * AST-walking, because the dispatch chain crosses 3 files and involves
 * both synchronous calls and event-driven broadcasting.
 */
export function extractMessageFlows(): MessageFlow[] {
  return [
    {
      clientMessageType: "join",
      description: "Player connects and joins the game world",
      steps: [
        {
          lane: "Client",
          action: "User enters name and clicks Join",
          method: "connect()",
          fileId: "client/src/network.ts",
          producesKind: "command",
          produces: "join",
          dataShape: "{ name: string; description?: string }",
        },
        {
          lane: "Network",
          action: "WebSocket receives join message",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 197,
          producesKind: "command",
          produces: "spawn",
          errorPaths: [
            { condition: "Already joined", produces: "error" },
          ],
          dataShape: "{ name, x, y, isNpc?, description? }",
        },
        {
          lane: "Network",
          action: "Sends preview player_joined to joining client",
          method: "send()",
          fileId: "server/src/network/websocket.ts",
          line: 238,
          producesKind: "serverMessage",
          produces: "player_joined",
          dataShape: "Player { id, name, x, y, state }",
        },
        {
          lane: "Engine",
          action: "Command queue processes spawn command",
          method: "processCommands()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 342,
          producesKind: "event",
          produces: "spawn",
        },
        {
          lane: "Engine",
          action: "Creates player at spawn point",
          method: "spawnPlayer()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 119,
          producesKind: "event",
          produces: "spawn",
        },
        {
          lane: "Network",
          action: "Broadcasts player_joined to all clients",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 86,
          producesKind: "serverMessage",
          produces: "player_joined",
          dataShape: "Player { id, name, x, y, state }",
        },
      ],
    },
    {
      clientMessageType: "input_start",
      description: "Player presses a WASD/arrow key to begin moving",
      steps: [
        {
          lane: "Client",
          action: "Keydown event fires for WASD/arrow key",
          method: "handleKeyDown()",
          fileId: "client/src/main.ts",
          producesKind: "command",
          produces: "input_start",
          dataShape: "{ direction: MoveDirection }",
          stateTransition: { machineId: "player", from: "idle", to: "walking" },
        },
        {
          lane: "Client",
          action: "Client-side prediction starts immediately",
          method: "predictMovement()",
          fileId: "client/src/prediction.ts",
          producesKind: "directCall",
        },
        {
          lane: "Network",
          action: "WebSocket receives input_start",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 265,
          producesKind: "directCall",
        },
        {
          lane: "Engine",
          action: "Toggles held key state, updates inputX/inputY",
          method: "setPlayerInput()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 291,
          producesKind: "event",
          produces: "input_state",
        },
        {
          lane: "Engine",
          action: "Next tick: velocity + AABB collision resolution",
          method: "processInputMovement()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 596,
          producesKind: "event",
          produces: "input_move",
        },
        {
          lane: "Engine",
          action: "Emits player_update for broadcasting",
          method: "tick()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 538,
          producesKind: "event",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
        {
          lane: "Network",
          action: "Broadcasts updated position to all clients",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 106,
          producesKind: "serverMessage",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
        {
          lane: "Client",
          action: "Reconciles server position with prediction",
          method: "reconcile()",
          fileId: "client/src/prediction.ts",
        },
      ],
    },
    {
      clientMessageType: "input_stop",
      description: "Player releases a WASD/arrow key",
      steps: [
        {
          lane: "Client",
          action: "Keyup event fires",
          method: "handleKeyUp()",
          fileId: "client/src/main.ts",
          producesKind: "command",
          produces: "input_stop",
          dataShape: "{ direction: MoveDirection }",
        },
        {
          lane: "Network",
          action: "WebSocket receives input_stop",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 271,
          producesKind: "directCall",
        },
        {
          lane: "Engine",
          action: "Clears held key, zeros velocity if no keys held",
          method: "setPlayerInput()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 291,
          producesKind: "event",
          produces: "input_state",
          stateTransition: { machineId: "player", from: "walking", to: "idle" },
        },
        {
          lane: "Network",
          action: "Broadcasts final position",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 106,
          producesKind: "serverMessage",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
      ],
    },
    {
      clientMessageType: "move",
      description: "Player click-to-moves to a tile (A* pathfinding)",
      steps: [
        {
          lane: "Client",
          action: "User clicks a tile on the map",
          method: "onTileClick()",
          fileId: "client/src/renderer.ts",
          producesKind: "command",
          produces: "move",
          dataShape: "{ x: number; y: number }",
        },
        {
          lane: "Network",
          action: "WebSocket receives move message",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 245,
          producesKind: "command",
          produces: "move_to",
          dataShape: "{ x: number; y: number }",
        },
        {
          lane: "Engine",
          action: "Command queue processes move_to",
          method: "processCommands()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 363,
          producesKind: "directCall",
          stateTransition: { machineId: "player", from: "idle", to: "walking" },
        },
        {
          lane: "Engine",
          action: "Computes A* path to destination",
          method: "setPlayerTarget()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 196,
          producesKind: "event",
          produces: "move_start",
        },
        {
          lane: "Engine",
          action: "Each tick: moves along path waypoints",
          method: "processMovement()",
          fileId: "server/src/engine/gameLoop.ts",
          producesKind: "event",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
        {
          lane: "Network",
          action: "Broadcasts position updates each tick",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 106,
          producesKind: "serverMessage",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
      ],
    },
    {
      clientMessageType: "start_convo",
      description: "Player initiates a conversation with another player/NPC",
      steps: [
        {
          lane: "Client",
          action: "User clicks 'Talk' on a nearby player",
          method: "startConversation()",
          fileId: "client/src/ui.ts",
          producesKind: "command",
          produces: "start_convo",
          dataShape: "{ targetId: string }",
        },
        {
          lane: "Network",
          action: "WebSocket receives start_convo, validates players",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 294,
          producesKind: "command",
          produces: "start_convo",
          errorPaths: [
            { condition: "Cannot talk to yourself", produces: "error" },
            { condition: "Target not found", produces: "error" },
            { condition: "You are already in a conversation", produces: "error" },
            { condition: "Target already in a conversation", produces: "error" },
          ],
        },
        {
          lane: "Engine",
          action: "Creates conversation in 'invited' state",
          method: "startConversation()",
          fileId: "server/src/engine/conversation.ts",
          line: 72,
          producesKind: "event",
          produces: "convo_started",
          stateTransition: { machineId: "conversation", from: "(new)", to: "invited" },
        },
        {
          lane: "Network",
          action: "Sends convo_update to both participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 122,
          producesKind: "serverMessage",
          produces: "convo_update",
          dataShape: "Conversation { id, player1Id, player2Id, state, messages[] }",
        },
        {
          lane: "NPC",
          action: "If target is NPC: auto-accepts invite",
          method: "processTick()",
          fileId: "server/src/engine/conversation.ts",
          line: 181,
          producesKind: "event",
          produces: "convo_accepted",
          stateTransition: { machineId: "conversation", from: "invited", to: "walking" },
        },
        {
          lane: "Engine",
          action: "Both players walk toward rendezvous point",
          method: "processTick()",
          fileId: "server/src/engine/conversation.ts",
          line: 201,
          producesKind: "event",
          produces: "convo_active",
          stateTransition: { machineId: "conversation", from: "walking", to: "active" },
        },
        {
          lane: "Network",
          action: "Sends convo_update (active) to participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 122,
          producesKind: "serverMessage",
          produces: "convo_update",
          dataShape: "Conversation { id, player1Id, player2Id, state, messages[] }",
        },
        {
          lane: "Client",
          action: "Shows conversation UI panel",
          method: "showConversation()",
          fileId: "client/src/ui.ts",
        },
      ],
    },
    {
      clientMessageType: "say",
      description: "Player sends a chat message in a conversation",
      steps: [
        {
          lane: "Client",
          action: "User types and submits a message",
          method: "sendMessage()",
          fileId: "client/src/ui.ts",
          producesKind: "command",
          produces: "say",
          dataShape: "{ convoId: number; content: string }",
        },
        {
          lane: "Network",
          action: "WebSocket receives say, validates active convo",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 277,
          producesKind: "command",
          produces: "say",
          errorPaths: [
            { condition: "Not in active conversation", produces: "error" },
          ],
          dataShape: "{ convoId: number; content: string }",
        },
        {
          lane: "Engine",
          action: "Adds message to conversation",
          method: "addMessage()",
          fileId: "server/src/engine/conversation.ts",
          line: 128,
          producesKind: "event",
          produces: "convo_message",
        },
        {
          lane: "Network",
          action: "Sends message to both participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 136,
          producesKind: "serverMessage",
          produces: "message",
          dataShape: "Message { id, convoId, playerId, content, tick }",
        },
        {
          lane: "NPC",
          action: "Orchestrator receives message event",
          method: "onConvoMessage()",
          fileId: "server/src/npc/orchestrator.ts",
          producesKind: "directCall",
        },
        {
          lane: "NPC",
          action: "Sets 'waiting for response' indicator",
          method: "setPlayerWaitingForResponse()",
          fileId: "server/src/engine/gameLoop.ts",
          producesKind: "event",
          produces: "player_update",
        },
        {
          lane: "NPC",
          action: "Retrieves relevant memories (recency x importance x similarity)",
          method: "retrieveRelevantMemories()",
          fileId: "server/src/npc/memory.ts",
          producesKind: "directCall",
        },
        {
          lane: "Persistence",
          action: "Vector similarity search on pgvector embeddings",
          method: "searchMemories()",
          fileId: "server/src/db/npcStore.ts",
          producesKind: "directCall",
        },
        {
          lane: "NPC",
          action: "Generates reply via Claude CLI subprocess",
          method: "generateReply()",
          fileId: "server/src/npc/claudeCodeProvider.ts",
          producesKind: "command",
          produces: "say",
          dataShape: "{ convoId: number; content: string }",
        },
        {
          lane: "Engine",
          action: "NPC reply enqueued as 'say' command",
          method: "enqueue()",
          fileId: "server/src/engine/gameLoop.ts",
          producesKind: "event",
          produces: "convo_message",
        },
        {
          lane: "Network",
          action: "Broadcasts NPC reply to participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 136,
          producesKind: "serverMessage",
          produces: "message",
          dataShape: "Message { id, convoId, playerId, content, tick }",
        },
      ],
    },
    {
      clientMessageType: "accept_convo",
      description: "Player accepts a conversation invite",
      steps: [
        {
          lane: "Client",
          action: "User clicks Accept on invite notification",
          method: "acceptConversation()",
          fileId: "client/src/ui.ts",
          producesKind: "command",
          produces: "accept_convo",
          dataShape: "{ convoId: number }",
        },
        {
          lane: "Network",
          action: "WebSocket receives accept_convo, validates invite",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 321,
          producesKind: "command",
          produces: "accept_convo",
          errorPaths: [
            { condition: "Invite no longer available", produces: "error" },
            { condition: "Only invitee can accept", produces: "error" },
          ],
        },
        {
          lane: "Engine",
          action: "Transitions conversation: invited -> walking",
          method: "acceptInvite()",
          fileId: "server/src/engine/conversation.ts",
          line: 103,
          producesKind: "event",
          produces: "convo_accepted",
          stateTransition: { machineId: "conversation", from: "invited", to: "walking" },
        },
        {
          lane: "Network",
          action: "Sends convo_update to participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 122,
          producesKind: "serverMessage",
          produces: "convo_update",
          dataShape: "Conversation { id, player1Id, player2Id, state, messages[] }",
        },
      ],
    },
    {
      clientMessageType: "decline_convo",
      description: "Player declines a conversation invite",
      steps: [
        {
          lane: "Client",
          action: "User clicks Decline on invite notification",
          method: "declineConversation()",
          fileId: "client/src/ui.ts",
          producesKind: "command",
          produces: "decline_convo",
          dataShape: "{ convoId: number }",
        },
        {
          lane: "Network",
          action: "WebSocket receives decline_convo, validates invite",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 344,
          producesKind: "command",
          produces: "decline_convo",
          errorPaths: [
            { condition: "Invite no longer available", produces: "error" },
            { condition: "Only invitee can decline", produces: "error" },
          ],
        },
        {
          lane: "Engine",
          action: "Transitions conversation: invited -> ended (declined)",
          method: "declineInvite()",
          fileId: "server/src/engine/conversation.ts",
          line: 115,
          producesKind: "event",
          produces: "convo_declined",
          stateTransition: { machineId: "conversation", from: "invited", to: "ended" },
        },
        {
          lane: "Engine",
          action: "Frees both players from conversation",
          method: "endConversation()",
          fileId: "server/src/engine/conversation.ts",
          line: 152,
          producesKind: "event",
          produces: "convo_ended",
        },
      ],
    },
    {
      clientMessageType: "end_convo",
      description: "Player ends an active conversation",
      steps: [
        {
          lane: "Client",
          action: "User clicks End Conversation",
          method: "endConversation()",
          fileId: "client/src/ui.ts",
          producesKind: "command",
          produces: "end_convo",
          dataShape: "{ convoId: number }",
        },
        {
          lane: "Network",
          action: "WebSocket receives end_convo",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 365,
          producesKind: "command",
          produces: "end_convo",
          errorPaths: [
            { condition: "Not in a conversation", produces: "error" },
          ],
        },
        {
          lane: "Engine",
          action: "Ends conversation, frees both players",
          method: "endConversation()",
          fileId: "server/src/engine/conversation.ts",
          line: 152,
          producesKind: "event",
          produces: "convo_ended",
          stateTransition: { machineId: "conversation", from: "active", to: "ended" },
        },
        {
          lane: "NPC",
          action: "Orchestrator stores conversation memories",
          method: "onConvoEnded()",
          fileId: "server/src/npc/orchestrator.ts",
          producesKind: "directCall",
        },
        {
          lane: "Persistence",
          action: "Saves memories with embeddings to PostgreSQL",
          method: "storeMemory()",
          fileId: "server/src/db/npcStore.ts",
          producesKind: "directCall",
        },
        {
          lane: "Network",
          action: "Sends convo_update (ended) to participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 122,
          producesKind: "serverMessage",
          produces: "convo_update",
          dataShape: "Conversation { id, player1Id, player2Id, state, messages[] }",
        },
      ],
    },
    {
      clientMessageType: "move_direction",
      description: "Player moves one tile in a direction (legacy/mobile)",
      steps: [
        {
          lane: "Client",
          action: "Sends single-tile move request",
          method: "moveDirection()",
          fileId: "client/src/network.ts",
          producesKind: "command",
          produces: "move_direction",
          dataShape: "{ direction: MoveDirection }",
        },
        {
          lane: "Network",
          action: "WebSocket receives move_direction",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 255,
          producesKind: "command",
          produces: "move_direction",
        },
        {
          lane: "Engine",
          action: "Moves player one tile with collision check",
          method: "movePlayerDirection()",
          fileId: "server/src/engine/gameLoop.ts",
          line: 229,
          producesKind: "event",
          produces: "move_direction",
        },
        {
          lane: "Network",
          action: "Broadcasts updated position",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 106,
          producesKind: "serverMessage",
          produces: "player_update",
          dataShape: "Player { id, x, y, vx, vy, state, orientation }",
        },
      ],
    },
    {
      clientMessageType: "ping",
      description: "Keepalive ping (no response)",
      steps: [
        {
          lane: "Client",
          action: "Periodic keepalive",
          method: "ping()",
          fileId: "client/src/network.ts",
          producesKind: "command",
          produces: "ping",
        },
        {
          lane: "Network",
          action: "WebSocket receives and ignores ping",
          method: "onMessage()",
          fileId: "server/src/network/websocket.ts",
          line: 382,
        },
      ],
    },
    // --- Improvement 6: New flows ---
    {
      clientMessageType: "npc_initiate",
      description: "NPC autonomously starts a conversation with a nearby idle player",
      steps: [
        {
          lane: "NPC",
          action: "Orchestrator checks for nearby idle players every 20 ticks",
          method: "maybeInitiateConversations()",
          fileId: "server/src/npc/orchestrator.ts",
          producesKind: "directCall",
        },
        {
          lane: "NPC",
          action: "Selects target and enqueues start_convo command",
          method: "enqueue()",
          fileId: "server/src/npc/orchestrator.ts",
          producesKind: "command",
          produces: "start_convo",
          dataShape: "{ targetId: string }",
        },
        {
          lane: "Engine",
          action: "Creates conversation in 'invited' state",
          method: "startConversation()",
          fileId: "server/src/engine/conversation.ts",
          line: 72,
          producesKind: "event",
          produces: "convo_started",
          stateTransition: { machineId: "conversation", from: "(new)", to: "invited" },
        },
        {
          lane: "Network",
          action: "Broadcasts convo_update to participants",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          line: 122,
          producesKind: "serverMessage",
          produces: "convo_update",
          dataShape: "Conversation { id, player1Id, player2Id, state, messages[] }",
        },
      ],
    },
    {
      clientMessageType: "disconnect",
      description: "Player's WebSocket connection closes",
      steps: [
        {
          lane: "Client",
          action: "WebSocket connection closes (browser tab closed, network loss)",
          method: "ws.onclose",
          fileId: "client/src/network.ts",
          producesKind: "directCall",
        },
        {
          lane: "Network",
          action: "Server detects WebSocket close event",
          method: "ws.on('close')",
          fileId: "server/src/network/websocket.ts",
          producesKind: "directCall",
        },
        {
          lane: "Engine",
          action: "If player is in conversation, enqueue end_convo",
          method: "enqueue()",
          fileId: "server/src/network/websocket.ts",
          producesKind: "command",
          produces: "end_convo",
          stateTransition: { machineId: "conversation", from: "active", to: "ended" },
        },
        {
          lane: "Engine",
          action: "Enqueues remove command for the disconnected player",
          method: "enqueue()",
          fileId: "server/src/network/websocket.ts",
          producesKind: "command",
          produces: "remove",
        },
        {
          lane: "Engine",
          action: "Removes player from simulation, emits despawn event",
          method: "removePlayer()",
          fileId: "server/src/engine/gameLoop.ts",
          producesKind: "event",
          produces: "despawn",
        },
        {
          lane: "Network",
          action: "Broadcasts player_left to remaining clients",
          method: "broadcastGameEvent()",
          fileId: "server/src/network/websocket.ts",
          producesKind: "serverMessage",
          produces: "player_left",
        },
      ],
    },
  ];
}

/**
 * Build message flow groups for organizing related flows.
 */
export function extractMessageFlowGroups(): MessageFlowGroup[] {
  return [
    {
      id: "conversation",
      label: "Conversation",
      description:
        "Complete conversation lifecycle: invite -> accept/decline -> walk -> chat -> end. " +
        "NPCs auto-accept invites. Messages trigger NPC replies via Claude.",
      flowTypes: ["start_convo", "accept_convo", "decline_convo", "say", "end_convo", "npc_initiate"],
    },
    {
      id: "movement",
      label: "Movement",
      description:
        "Two movement systems: WASD keys (input_start/stop -> velocity + collision) and " +
        "click-to-move (move -> A* pathfinding). Both produce player_update broadcasts.",
      flowTypes: ["input_start", "input_stop", "move", "move_direction"],
    },
    {
      id: "lifecycle",
      label: "Lifecycle",
      description:
        "Player connection and disconnection. Join spawns a player at a map spawn point. " +
        "Disconnect cleans up conversations and removes the player.",
      flowTypes: ["join", "disconnect", "ping"],
    },
  ];
}
